"""Simulation 21: temporal aggregation under explicitly nonzero true contrast.

Companion to sim04 (which had Delta_beta_true ~ -0.031 at the thinnest
resolution). Here the herbivore and predator guilds differ in true
ecological spatial turnover BEFORE aggregation, generated by giving
the two guilds different mean range breadths (a genuine ecological
difference, not a structural asymmetry): narrower ranges -> higher
within-guild beta diversity.

Scenarios (prospectively specified targets):
    weak     ~ -0.05 : herb breadth 0.30, pred breadth 0.45
    moderate ~ -0.10 : herb breadth 0.30, pred breadth 0.70
    strong   ~ -0.20 : herb breadth 0.15, pred breadth 0.90
Pool sizes follow sim04 (N_H = 26, N_P = 12).

Aggregation rule identical to sim04: 8 independent thin slices per
taxon -> bins of 8, 4, 2, 1 slice(s) via slice-wise OR pooling.
Attenuation fraction = 1 - |delta_beta_pooled| / |delta_beta_thin|
computed on replicate means (thin = 8 bins).

Frozen seed 20260925, 150 replicates.
Output: results/tables/sim21_temporal_attenuation.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sim_core import gen_taxon, mean_beta_jaccard

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

RNG_SEED = 20260925
N_LOC = 200
N_H, N_P = 26, 12
OCC_P = 0.4
T_SLICES = 8
REPS = 150

SCENARIOS = {  # label: (herb breadth, pred breadth)
    "weak":     (0.30, 0.45),
    "moderate": (0.30, 0.70),
    "strong":   (0.15, 0.90),
}


def slice_guild(n_taxa, breadth, rng):
    return np.stack(
        [gen_taxon(N_LOC, breadth, OCC_P, rng) for _ in range(n_taxa)],
        axis=1)


def run_scenario(bh, bp, rng):
    """Return dict n_bins -> array of replicate delta_beta values."""
    out = {}
    for n_bins in (8, 4, 2, 1):
        group = T_SLICES // n_bins
        vals = []
        for _ in range(REPS):
            mh_bins, mp_bins = [], []
            for b in range(n_bins):
                mh = np.zeros((N_LOC, N_H))
                mp = np.zeros((N_LOC, N_P))
                for s in range(group):
                    mh = np.maximum(mh, slice_guild(N_H, bh, rng))
                    mp = np.maximum(mp, slice_guild(N_P, bp, rng))
                mh_b = mh[mh.sum(axis=1) > 0]
                mp_b = mp[mp.sum(axis=1) > 0]
                mh_bins.append(mean_beta_jaccard(mh_b))
                mp_bins.append(mean_beta_jaccard(mp_b))
            vals.append(np.mean(mp_bins) - np.mean(mh_bins))
        out[n_bins] = np.asarray(vals)
    return out


def main() -> None:
    rng = np.random.default_rng(RNG_SEED)
    rows = []
    for label, (bh, bp) in SCENARIOS.items():
        res = run_scenario(bh, bp, rng)
        thin_mean = abs(res[8].mean())
        for n_bins in (8, 4, 2, 1):
            v = res[n_bins]
            rows.append({
                "scenario": label,
                "breadth_herb": bh,
                "breadth_pred": bp,
                "temporal_bins": n_bins,
                "delta_beta_mean": v.mean(),
                "lo95": np.quantile(v, 0.025),
                "hi95": np.quantile(v, 0.975),
                "abs_vs_thin_fraction": abs(v.mean()) / thin_mean,
                "attenuation_fraction": 1 - abs(v.mean()) / thin_mean,
            })
    df = pd.DataFrame(rows)
    df.to_csv(OUT / "sim21_temporal_attenuation.csv", index=False)
    print(df.to_string(index=False))


if __name__ == "__main__":
    main()
